// © 2025 Kamenyari. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace NotoGameplayTags
{
	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sneak);
	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);

	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Run);
	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Sneak);

	NOTOMORROWGAME_API	UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseTag_Movement);
}
