// © 2025 Kamenyari. All rights reserved.

#pragma once

#include "NativeGameplayTags.h"

namespace NotoGameplayTags
{
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sneak);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_InteractModified);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Drop);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload);

	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Run);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(MovementState_Sneak);

	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseTag_Movement);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(NoiseTag_Gunfire);

	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Magazine_Light);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Magazine_Heavy);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ammo_Shell);

	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Data_Damage);
	NOTOMORROWGAME_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Dead);
}
